"""Enumeraciones del modelo de datos (§6). Se almacenan como VARCHAR (no ENUM nativo)
para mantener portabilidad entre MariaDB (producción) y SQLite (pruebas)."""
import enum


class TipoCuenta(str, enum.Enum):
    AD = "AD"
    LOCAL = "LOCAL"
    PROVEEDOR = "PROVEEDOR"


class CoberturaGeografica(str, enum.Enum):
    NACIONAL = "NACIONAL"
    REGIONAL = "REGIONAL"
    LOCAL = "LOCAL"


class EstadoContratoOperadora(str, enum.Enum):
    ACTIVO = "ACTIVO"
    CADUCADO = "CADUCADO"
    SUSPENDIDO = "SUSPENDIDO"
    EN_RENOVACION = "EN_RENOVACION"
    EN_JURIDICO = "EN_JURIDICO"


class EstadoContrato(str, enum.Enum):
    VIGENTE = "VIGENTE"
    EN_RENOVACION = "EN_RENOVACION"
    TERMINADO = "TERMINADO"
    SUSPENDIDO = "SUSPENDIDO"
    EN_JURIDICO = "EN_JURIDICO"


class TipoZona(str, enum.Enum):
    CAPITAL_PROVINCIAL = "CAPITAL_PROVINCIAL"
    CABECERA_CANTONAL = "CABECERA_CANTONAL"
    OTRO_SECTOR = "OTRO_SECTOR"


class EstadoPago(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    PARCIAL = "PARCIAL"
    COMPLETO = "COMPLETO"


class TipoSolicitud(str, enum.Enum):
    NUEVO_CONTRATO = "NUEVO_CONTRATO"
    AMPLIACION = "AMPLIACION"


class DirigidaA(str, enum.Enum):
    GERENTE_GENERAL = "GERENTE_GENERAL"
    ADMIN_UNIDAD_NEGOCIO = "ADMIN_UNIDAD_NEGOCIO"
    ADMIN_CONTRATO = "ADMIN_CONTRATO"


class EstadoSolicitud(str, enum.Enum):
    BORRADOR = "BORRADOR"
    RECEPCION = "RECEPCION"
    REVISION_TECNICA = "REVISION_TECNICA"
    APROBACION_GERENCIAL = "APROBACION_GERENCIAL"
    REVISION_JURIDICA = "REVISION_JURIDICA"
    AUTORIZACION_FINAL = "AUTORIZACION_FINAL"
    FINALIZADA = "FINALIZADA"
    OBSERVADA = "OBSERVADA"
    RECHAZADA = "RECHAZADA"


class EntidadTipoDocumento(str, enum.Enum):
    SOLICITUD = "SOLICITUD"
    CONTRATO = "CONTRATO"
    ALQUILER = "ALQUILER"
    NOVEDAD = "NOVEDAD"
    OPERADORA = "OPERADORA"
    PAGO = "PAGO"


class TipoDocumento(str, enum.Enum):
    SOLICITUD_FORMAL = "SOLICITUD_FORMAL"
    TITULO_HABILITANTE = "TITULO_HABILITANTE"
    DOC_SOCIETARIA = "DOC_SOCIETARIA"
    RUC = "RUC"
    CEDULA_REP_LEGAL = "CEDULA_REP_LEGAL"
    COMPROBANTE_PAGO_ENERGIA = "COMPROBANTE_PAGO_ENERGIA"
    POLIZA = "POLIZA"
    PLAN_EXPANSION = "PLAN_EXPANSION"
    SIG_GEODATABASE = "SIG_GEODATABASE"
    ESPEC_TECNICAS = "ESPEC_TECNICAS"
    LISTADO_CONTACTOS = "LISTADO_CONTACTOS"
    CONTRATO_FIRMADO = "CONTRATO_FIRMADO"
    INFORME_FACTIBILIDAD = "INFORME_FACTIBILIDAD"
    FOTO_PLACAS = "FOTO_PLACAS"
    OTRO = "OTRO"


class EstadoValidacionDocumento(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    VALIDADO = "VALIDADO"
    OBSERVADO = "OBSERVADO"
    RECHAZADO = "RECHAZADO"


class EtapaAutorizacion(str, enum.Enum):
    RECEPCION = "RECEPCION"
    REVISION_TECNICA = "REVISION_TECNICA"
    APROBACION_GERENCIAL = "APROBACION_GERENCIAL"
    REVISION_JURIDICA = "REVISION_JURIDICA"
    AUTORIZACION_FINAL = "AUTORIZACION_FINAL"


class EstadoAutorizacion(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    OBSERVADO = "OBSERVADO"


class EstadoFactura(str, enum.Enum):
    EMITIDA = "EMITIDA"
    PAGADA = "PAGADA"
    VENCIDA = "VENCIDA"
    PARCIAL = "PARCIAL"
    ANULADA = "ANULADA"


class TipoPago(str, enum.Enum):
    PARCIAL = "PARCIAL"
    TOTAL = "TOTAL"


class MetodoPago(str, enum.Enum):
    TRANSFERENCIA = "TRANSFERENCIA"
    DEPOSITO = "DEPOSITO"
    CHEQUE = "CHEQUE"
    TARJETA = "TARJETA"
    VENTANILLA = "VENTANILLA"
    PASARELA = "PASARELA"


class TipoNovedad(str, enum.Enum):
    INSPECCION_PROGRAMADA = "INSPECCION_PROGRAMADA"
    DANO_REPORTADO = "DANO_REPORTADO"
    MANTENIMIENTO = "MANTENIMIENTO"


class EstadoNovedad(str, enum.Enum):
    PROGRAMADA = "PROGRAMADA"
    EN_PROCESO = "EN_PROCESO"
    EJECUTADA = "EJECUTADA"
    CERRADA = "CERRADA"


class TipoAlerta(str, enum.Enum):
    VENCIMIENTO_CONTRATO = "VENCIMIENTO_CONTRATO"
    VENCIMIENTO_POLIZA = "VENCIMIENTO_POLIZA"
    MOROSIDAD = "MOROSIDAD"
    VENCIMIENTO_TITULO = "VENCIMIENTO_TITULO"
    SIG_ANUAL_PENDIENTE = "SIG_ANUAL_PENDIENTE"


class SeveridadAlerta(str, enum.Enum):
    INFO = "INFO"
    ADVERTENCIA = "ADVERTENCIA"
    CRITICA = "CRITICA"


class AccionAuditoria(str, enum.Enum):
    CREAR = "CREAR"
    EDITAR = "EDITAR"
    ELIMINAR = "ELIMINAR"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    DESCARGA = "DESCARGA"
    ACCESO_DATO_SENSIBLE = "ACCESO_DATO_SENSIBLE"
