"""modelo inicial sgaie

Revision ID: f4116961e7ad
Revises: 
Create Date: 2026-06-25 03:38:48.458660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4116961e7ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_canon',
    sa.Column('tipo_zona', sa.Enum('CAPITAL_PROVINCIAL', 'CABECERA_CANTONAL', 'OTRO_SECTOR', name='tipozona', native_enum=False, length=40), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('referencia_normativa', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_catalogo_canon_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_catalogo_canon_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('entidad_tipo', sa.Enum('SOLICITUD', 'CONTRATO', 'ALQUILER', 'NOVEDAD', 'OPERADORA', 'PAGO', name='entidadtipodocumento', native_enum=False, length=40), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('SOLICITUD_FORMAL', 'TITULO_HABILITANTE', 'DOC_SOCIETARIA', 'RUC', 'CEDULA_REP_LEGAL', 'COMPROBANTE_PAGO_ENERGIA', 'POLIZA', 'PLAN_EXPANSION', 'SIG_GEODATABASE', 'ESPEC_TECNICAS', 'LISTADO_CONTACTOS', 'CONTRATO_FIRMADO', 'INFORME_FACTIBILIDAD', 'FOTO_PLACAS', 'OTRO', name='tipodocumento', native_enum=False, length=50), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('estado_validacion', sa.Enum('PENDIENTE', 'VALIDADO', 'OBSERVADO', 'RECHAZADO', name='estadovalidaciondocumento', native_enum=False, length=40), nullable=False),
    sa.Column('observacion_validacion', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_documento_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_documento_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_entidad_id'), 'documento', ['entidad_id'], unique=False)
    op.create_table('permiso',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_permiso_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_permiso_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=True)
    op.create_table('rol',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_rol_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_rol_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_codigo'), 'rol', ['codigo'], unique=True)
    op.create_table('unidad_negocio',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_unidad_negocio_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_unidad_negocio_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidad_negocio_codigo'), 'unidad_negocio', ['codigo'], unique=True)
    op.create_table('alerta',
    sa.Column('tipo', sa.Enum('VENCIMIENTO_CONTRATO', 'VENCIMIENTO_POLIZA', 'MOROSIDAD', 'VENCIMIENTO_TITULO', 'SIG_ANUAL_PENDIENTE', name='tipoalerta', native_enum=False, length=40), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('severidad', sa.Enum('INFO', 'ADVERTENCIA', 'CRITICA', name='severidadalerta', native_enum=False, length=40), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_alerta_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_alerta_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_entidad_id'), 'alerta', ['entidad_id'], unique=False)
    op.create_table('cable_operadora',
    sa.Column('numero_registro', sa.String(length=50), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=250), nullable=False),
    sa.Column('ruc', app.db.base.ValorCifrado(length=180), nullable=True),
    sa.Column('cuenta_contrato', sa.String(length=50), nullable=True),
    sa.Column('representante_legal', sa.String(length=200), nullable=True),
    sa.Column('representante_cedula', app.db.base.ValorCifrado(length=180), nullable=True),
    sa.Column('titulo_habilitante_numero', sa.String(length=100), nullable=True),
    sa.Column('titulo_habilitante_vigencia', sa.Date(), nullable=True),
    sa.Column('arcotel_resolucion', sa.String(length=150), nullable=True),
    sa.Column('servicios_autorizados', sa.Text(), nullable=True),
    sa.Column('cobertura_geografica', sa.Enum('NACIONAL', 'REGIONAL', 'LOCAL', name='coberturageografica', native_enum=False, length=40), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('estado_contrato', sa.Enum('ACTIVO', 'CADUCADO', 'SUSPENDIDO', 'EN_RENOVACION', 'EN_JURIDICO', name='estadocontratooperadora', native_enum=False, length=40), nullable=False),
    sa.Column('fecha_firma_contrato', sa.Date(), nullable=True),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('administrador_contrato_id', sa.Integer(), nullable=True),
    sa.Column('administrador_contrato_texto', sa.String(length=200), nullable=True),
    sa.Column('tipo_contrato', sa.Enum('NACIONAL', 'REGIONAL', 'LOCAL', name='coberturageografica', native_enum=False, length=40), nullable=False),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_cable_operadora_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['administrador_contrato_id'], ['usuario.id'], name='fk_cable_operadora_administrador_contrato', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_cable_operadora_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cable_operadora_numero_registro'), 'cable_operadora', ['numero_registro'], unique=True)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_rol_permiso_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_rol_permiso_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permiso')
    )
    op.create_table('contrato',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=False),
    sa.Column('tipo_cobertura', sa.Enum('NACIONAL', 'REGIONAL', 'LOCAL', name='coberturageografica', native_enum=False, length=40), nullable=False),
    sa.Column('fecha_suscripcion', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('VIGENTE', 'EN_RENOVACION', 'TERMINADO', 'SUSPENDIDO', 'EN_JURIDICO', name='estadocontrato', native_enum=False, length=40), nullable=False),
    sa.Column('total_postes', sa.Integer(), nullable=False),
    sa.Column('total_ductos_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('canon_anual_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('poliza_numero', sa.String(length=100), nullable=True),
    sa.Column('poliza_aseguradora', sa.String(length=200), nullable=True),
    sa.Column('poliza_valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('poliza_vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('poliza_vigencia_fin', sa.Date(), nullable=True),
    sa.Column('archivo_contrato_id', sa.Integer(), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('informe_factibilidad_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_contrato_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['archivo_contrato_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_contrato_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['informe_factibilidad_id'], ['informe_factibilidad.id'], name='fk_contrato_informe_factibilidad', use_alter=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], name='fk_contrato_solicitud', use_alter=True),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato')
    )
    op.create_table('nombre_comercial',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_nombre_comercial_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_nombre_comercial_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsable_tecnico_zona',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cedula', app.db.base.ValorCifrado(length=180), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('zona_cobertura', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_responsable_tecnico_zona_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_responsable_tecnico_zona_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefono_operadora',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_telefono_operadora_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_telefono_operadora_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('tipo_cuenta', sa.Enum('AD', 'LOCAL', 'PROVEEDOR', name='tipocuenta', native_enum=False, length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=True),
    sa.Column('cable_operadora_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_usuario_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_usuario_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('alquiler_anual',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('postes_sig', sa.Integer(), nullable=False),
    sa.Column('postes_fisicos', sa.Integer(), nullable=False),
    sa.Column('monto_facturado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_recaudado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_pendiente_recaudar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_facturacion', sa.Date(), nullable=True),
    sa.Column('estado_pago', sa.Enum('PENDIENTE', 'PARCIAL', 'COMPLETO', name='estadopago', native_enum=False, length=40), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('poliza_garantia_fecha', sa.Date(), nullable=True),
    sa.Column('poliza_garantia_archivo_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_alquiler_anual_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_alquiler_anual_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['poliza_garantia_archivo_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cable_operadora_id', 'anio', name='uq_alquiler_anual_operadora_anio')
    )
    op.create_index(op.f('ix_alquiler_anual_anio'), 'alquiler_anual', ['anio'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.Enum('CREAR', 'EDITAR', 'ELIMINAR', 'LOGIN', 'LOGOUT', 'DESCARGA', 'ACCESO_DATO_SENSIBLE', name='accionauditoria', native_enum=False, length=40), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('valores_antes', sa.JSON(), nullable=True),
    sa.Column('valores_despues', sa.JSON(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_log_auditoria_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_log_auditoria_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_entidad_id'), 'log_auditoria', ['entidad_id'], unique=False)
    op.create_table('novedad',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INSPECCION_PROGRAMADA', 'DANO_REPORTADO', 'MANTENIMIENTO', name='tiponovedad', native_enum=False, length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_ejecucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'EN_PROCESO', 'EJECUTADA', 'CERRADA', name='estadonovedad', native_enum=False, length=40), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ficha_informe_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_novedad_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_novedad_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['ficha_informe_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud',
    sa.Column('numero_referencia', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('NUEVO_CONTRATO', 'AMPLIACION', name='tiposolicitud', native_enum=False, length=40), nullable=False),
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=False),
    sa.Column('dirigida_a', sa.Enum('GERENTE_GENERAL', 'ADMIN_UNIDAD_NEGOCIO', 'ADMIN_CONTRATO', name='dirigidaa', native_enum=False, length=40), nullable=False),
    sa.Column('cobertura', sa.Enum('NACIONAL', 'REGIONAL', 'LOCAL', name='coberturageografica', native_enum=False, length=40), nullable=False),
    sa.Column('provincias_involucradas', sa.Text(), nullable=True),
    sa.Column('postes_solicitados', sa.Integer(), nullable=False),
    sa.Column('ductos_solicitados_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('objetivo_proyecto', sa.Text(), nullable=True),
    sa.Column('tipo_redes', sa.String(length=100), nullable=True),
    sa.Column('cronograma_inicio', sa.Date(), nullable=True),
    sa.Column('cronograma_fin', sa.Date(), nullable=True),
    sa.Column('puesta_en_servicio', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'RECEPCION', 'REVISION_TECNICA', 'APROBACION_GERENCIAL', 'REVISION_JURIDICA', 'AUTORIZACION_FINAL', 'FINALIZADA', 'OBSERVADA', 'RECHAZADA', name='estadosolicitud', native_enum=False, length=40), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_solicitud_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_solicitud_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_numero_referencia'), 'solicitud', ['numero_referencia'], unique=True)
    op.create_table('token_refresco_revocado',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_token_refresco_revocado_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_token_refresco_revocado_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_refresco_revocado_jti'), 'token_refresco_revocado', ['jti'], unique=True)
    op.create_table('autorizacion',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.Enum('RECEPCION', 'REVISION_TECNICA', 'APROBACION_GERENCIAL', 'REVISION_JURIDICA', 'AUTORIZACION_FINAL', name='etapaautorizacion', native_enum=False, length=40), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVADO', name='estadoautorizacion', native_enum=False, length=40), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_autorizacion_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_autorizacion_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacto_solicitud',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('rol_contacto', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_contacto_solicitud_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_contacto_solicitud_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('alquiler_anual_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('EMITIDA', 'PAGADA', 'VENCIDA', 'PARCIAL', 'ANULADA', name='estadofactura', native_enum=False, length=40), nullable=False),
    sa.Column('archivo_xml_id', sa.Integer(), nullable=True),
    sa.Column('archivo_pdf_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_factura_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['alquiler_anual_id'], ['alquiler_anual.id'], ),
    sa.ForeignKeyConstraint(['archivo_pdf_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['archivo_xml_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_factura_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('fotografia_novedad',
    sa.Column('novedad_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_fotografia_novedad_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_fotografia_novedad_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['novedad_id'], ['novedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informe_factibilidad',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=False),
    sa.Column('codigo_oficio', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cobertura', sa.Enum('NACIONAL', 'REGIONAL', 'LOCAL', name='coberturageografica', native_enum=False, length=40), nullable=False),
    sa.Column('postes_solicitados', sa.Integer(), nullable=False),
    sa.Column('postes_viables', sa.Integer(), nullable=False),
    sa.Column('postes_no_viables', sa.Integer(), nullable=False),
    sa.Column('ductos_solicitados_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ductos_viables_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ductos_no_viables_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('porcentaje_factibilidad', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revision_documental_estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_ultima_subsanacion', sa.Date(), nullable=True),
    sa.Column('sig_validado', sa.Boolean(), nullable=False),
    sa.Column('sig_validador', sa.String(length=200), nullable=True),
    sa.Column('sig_fecha_validacion', sa.Date(), nullable=True),
    sa.Column('inspeccion_fecha_inicio', sa.Date(), nullable=True),
    sa.Column('inspeccion_fecha_fin', sa.Date(), nullable=True),
    sa.Column('rutas_verificadas', sa.Text(), nullable=True),
    sa.Column('personal_participante', sa.Text(), nullable=True),
    sa.Column('conclusiones', sa.Text(), nullable=True),
    sa.Column('archivo_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_informe_factibilidad_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['archivo_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_informe_factibilidad_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poste_por_zona',
    sa.Column('alquiler_anual_id', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('canton', sa.String(length=100), nullable=False),
    sa.Column('parroquia', sa.String(length=100), nullable=True),
    sa.Column('tipo_zona', sa.Enum('CAPITAL_PROVINCIAL', 'CABECERA_CANTONAL', 'OTRO_SECTOR', name='tipozona', native_enum=False, length=40), nullable=False),
    sa.Column('cantidad_postes', sa.Integer(), nullable=False),
    sa.Column('cantidad_ductos_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('canon_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_poste_por_zona_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['alquiler_anual_id'], ['alquiler_anual.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_poste_por_zona_creado_por_usuario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruta_propuesta',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('recinto', sa.String(length=100), nullable=True),
    sa.Column('ruta', sa.String(length=255), nullable=True),
    sa.Column('postes_usados', sa.Integer(), nullable=False),
    sa.Column('postes_nuevos', sa.Integer(), nullable=False),
    sa.Column('total_postes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_ruta_propuesta_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_ruta_propuesta_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjunto_autorizacion',
    sa.Column('autorizacion_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_adjunto_autorizacion_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['autorizacion_id'], ['autorizacion.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_adjunto_autorizacion_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('cable_operadora_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('PARCIAL', 'TOTAL', name='tipopago', native_enum=False, length=40), nullable=False),
    sa.Column('metodo', sa.Enum('TRANSFERENCIA', 'DEPOSITO', 'CHEQUE', 'TARJETA', 'VENTANILLA', 'PASARELA', name='metodopago', native_enum=False, length=40), nullable=False),
    sa.Column('referencia_transaccion', app.db.base.ValorCifrado(length=500), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('fecha_conciliacion', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_pago_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['cable_operadora_id'], ['cable_operadora.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_pago_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacion_informe_factibilidad',
    sa.Column('informe_factibilidad_id', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('cantones', sa.Text(), nullable=True),
    sa.Column('unidad_negocio_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], name='fk_ubicacion_informe_factibilidad_actualizado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name='fk_ubicacion_informe_factibilidad_creado_por_usuario', use_alter=True),
    sa.ForeignKeyConstraint(['informe_factibilidad_id'], ['informe_factibilidad.id'], ),
    sa.ForeignKeyConstraint(['unidad_negocio_id'], ['unidad_negocio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion_informe_factibilidad')
    op.drop_table('pago')
    op.drop_table('adjunto_autorizacion')
    op.drop_table('ruta_propuesta')
    op.drop_table('poste_por_zona')
    op.drop_table('informe_factibilidad')
    op.drop_table('fotografia_novedad')
    op.drop_table('factura')
    op.drop_table('contacto_solicitud')
    op.drop_table('autorizacion')
    op.drop_index(op.f('ix_token_refresco_revocado_jti'), table_name='token_refresco_revocado')
    op.drop_table('token_refresco_revocado')
    op.drop_index(op.f('ix_solicitud_numero_referencia'), table_name='solicitud')
    op.drop_table('solicitud')
    op.drop_table('novedad')
    op.drop_index(op.f('ix_log_auditoria_entidad_id'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_alquiler_anual_anio'), table_name='alquiler_anual')
    op.drop_table('alquiler_anual')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('telefono_operadora')
    op.drop_table('responsable_tecnico_zona')
    op.drop_table('nombre_comercial')
    op.drop_table('contrato')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_cable_operadora_numero_registro'), table_name='cable_operadora')
    op.drop_table('cable_operadora')
    op.drop_index(op.f('ix_alerta_entidad_id'), table_name='alerta')
    op.drop_table('alerta')
    op.drop_index(op.f('ix_unidad_negocio_codigo'), table_name='unidad_negocio')
    op.drop_table('unidad_negocio')
    op.drop_index(op.f('ix_rol_codigo'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_documento_entidad_id'), table_name='documento')
    op.drop_table('documento')
    op.drop_table('catalogo_canon')
    # ### end Alembic commands ###
